<?php 
    include_once('../templates/header.tpl'); 
?>
<div class="container">
    <h2>Login</h2>
    <form action="../controllers/login.controller.php" method="POST">
        <input type="text" name="username" placeholder="Ingrese su username..."/>
        <input type="password" name="password" placeholder="Ingrese su password..."/>
        <a href="register.phtml">¿No tienes cuenta? Registrate aqui </a>
        <button>Login</button>
    </form>
</div>
<?php include_once('../templates/footer.tpl'); ?>