<div class="formulario-productos">
    <div class="producto">
        <form action="addGabinete" method="POST">
            <h2>Agregue un nuevo producto:</h2>
            <input type="text" name="marcaGabinete"><h3>Ingrese marca del gabinete</h3></input>
            <input type="text" name="modeloGabinete"><h3>Ingrese modelo del gabinete</h3></input>
            <input type="text" name="tamañoGabinete"><h3>Ingrese tamaño del gabinete</h3></input>
            <input type="text" name="valorGabinete"><h3>Ingrese valor del gabinete (USD)</h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>
<div class="formulario-productos">
    <div class="producto">  
        <form action="deleteGabinete" method="POST">
            <h2>Elimine un producto por su ID:</h2>
            <input type="text" name="idGabinete"><h3></h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>