<?php include_once('header.tpl'); ?>
<div class="container">
    <h2>Login</h2>
    <form action="verify" method="POST" class="Usuarios">
        <div>  
            <h2>Usuario:</h2>
            <input type="text" name="username" placeholder="Ingrese su username..."/>
        </div>
        <div> 
            <h3>Contraseña:</h3>
            <input type="password" name="password" placeholder="Ingrese su password..."/>
        </div>
        <div>
            <button class="buton-login" type="submit">Ingresar</button>
            <a href="register">¿No tienes cuenta? Registrate aqui </a>
            <a href="index">O Tambien puedes ingresar como invitado</a>
        </div>

    </form>
</div>
<?php include_once('footer.tpl'); ?>