<?php include_once('header.tpl'); ?>
<div class="container">
    <h2>Login</h2>
    <form action="verify" method="POST">
        <input type="text" name="username" placeholder="Ingrese su username..."/>
        <input type="password" name="password" placeholder="Ingrese su password..."/>
        <a href="register">¿No tienes cuenta? Registrate aqui </a>
        <button type="submit">Ingresar</button>
        <a href="index">ingresar como invitado</a>
    </form>
</div>
<?php include_once('footer.tpl'); ?>