
<?php include_once('navbar.tpl'); ?>

<div class="centrar-formulario">    
    <div class="formulario">
        <h1>Iniciar Sesion</h1>
        <form action="verify" method="POST">
            <div class="campo">
                <label for="nombre">Nombre de usuario:</label>
                <input type="text"  name="username" placeholder="Nombre de usuario">
            </div>
            <div class="campo">
                <label for="email">Contraseña:</label>
                <input type="password" name="password" placeholder="Su Contraseña">
            </div>
            <div class="boton">
                <button type="submit">Iniciar Sesion</button>
            </div>
            <div class="invited">
                <a href="index">O Tambien puedes ingresar como invitado</a>   
            </div>
            <div class="not-user">            
                <a href="register">¿No tienes cuenta? Registrate aqui </a>
            </div>                

        </form>
    </div>
 </div>

<?php include_once('footer.tpl'); ?>