<div class="titulo"><h3>Sobre Nosotros:</h3></div>
<div class="container">
        <h2>Nuestra Historia</h2>
        <p>Somos 2 estudiantes de la carrera universitaria "TUDAI" de la Facultad de Ciencias Exactas. Actualmente cursando el segundo cuatrimestre y este es nuestro proyecto de Trabajo Practico Especial</p>

        <h2>Colaboradores</h2>
        <p>Agustin Lucas Ramirez</p>
        <p>Lucas Cueli Faijoo </p>

        <h2>Nuestro Proyecto</h2>
        <p>Nuestra idea fue crear una pagina parecida a una "Tienda de computacion", la cual nos parecio un buen desafio para combinarlo con parte de base de datos, la cual aun sigue en desarrollo por parte de ambos.</p>
    </div>