<?php 
    include_once('header.tpl'); 
?>
<div class="titulo"><h3>Sobre Nosotros:</h3></div>
<div class="container">
        <h2>Nuestra Historia</h2>
        <p>Somos 2 estudiantes de la carrera universitaria "TUDAI" de la Facultad de Ciencias Exactas.</p>

        <h2>Nuestro Equipo</h2>
        <p>Nuestro equipo está formado por profesionales altamente calificados y apasionados por lo que hacen. Trabajamos juntos para lograr los mejores resultados para nuestros clientes.</p>

        <h2>Nuestra Misión</h2>
        <p>Nuestra misión es satisfacer las necesidades de nuestros clientes y superar sus expectativas. Buscamos constantemente formas de mejorar y crecer en un mundo en constante evolución.</p>
    </div>
<?php include_once 'footer.tpl'; ?>