<div class="formulario-productos">
    <div class="producto">
        <form action="addGrafica" method="POST">
            <input type="text" name="marcaGrafica">Ingrese marca de la grafica</input>
            <input type="text" name="modeloGrafica">Ingrese modelo de la grafica</input>
            <input type="text" name="vramGrafica">Ingrese vram de la grafica</input>
            <input type="text" name="valorGrafica">Ingrese valor de la grafica (USD)</input>
            <input type="submit">Agregar</input>
        </form>
    </div>
</div>
<div class="formulario-productos">
    <div class="producto">  
        <form action="deleteGrafica" method="POST">
            <input type="text" name="idGraf">ingrese id de la grafica que desea eliminar</input>
            <input type="submit">Eliminar</input>
        </form>
    </div>
</div>