<div class="formulario-productos">
    <div class="producto">
        <form action="addGrafica" method="POST">
            <h2>Agregue un nuevo producto:</h2>
            <input type="text" name="marcaGrafica"><h3>Ingrese marca de la grafica</h3></input>
            <input type="text" name="modeloGrafica"><h3>Ingrese modelo de la grafica</h3></input>
            <input type="text" name="vramGrafica"><h3>Ingrese vram de la grafica</h3></input>
            <input type="text" name="valorGrafica"><h3>Ingrese valor de la grafica (USD)</h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>
<div class="formulario-productos">
    <div class="producto">  
        <form action="deleteGrafica" method="POST">
            <h2>Elimine un producto por su ID:</h2>
            <input type="text" name="idGraf"><h3></h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>