<div class="formulario-productos">
    <div class="producto">
        <form action="addProcesador" method="POST">
            <h2>Agregue un nuevo producto:</h2>
            <input type="text" name="marcaProce"><h3>Ingrese marca del procesador</h3></input>
            <input type="text" name="modeloProce"><h3>Ingrese modelo del procesador</h3></input>
            <input type="text" name="socketProce"><h3>Ingrese socket del procesador</h3></input>
            <input type="text" name="valorProce"><h3>Ingrese valor del procesador (USD)</h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>
<div class="formulario-productos">
    <div class="producto">  
        <form action="deleteProcesador" method="POST">
            <h2>Elimine un producto por su ID:</h2>
            <input type="text" name="idProce"><h3></h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>