<div class="formulario-productos">
    <div class="producto">
        <form action="addRam" method="POST">
            <h2>Agregue un nuevo producto:</h2>
            <input type="text" name="marcaRam"><h3>ingrese marca de la RAM</h3></input>
            <input type="text" name="tamañoRam"><h3>ingrese el tamaño de RAM (GB)</h3></input>
            <input type="text" name="velocidadRam"><h3>ingrese velocidad de la RAM (MHz)</h3></input>
            <input type="text" name="generacionRam"><h3>ingrese generacion de la RAM</h3></input>
            <input type="text" name="valorRam"><h3>ingrese valor de la RAM (USD)</h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>
<div class="formulario-productos">
    <div class="producto">  
        <form action="deleteRam" method="POST">
            <h2>Elimine un producto por su ID:</h2>
            <input type="text" name="idRam"><h3></h3></input>
            <input type="submit" class="button_slide slide_left"></input>
        </form>
    </div>
</div>