<?php include_once('header.tpl'); ?>
    <div class="centrar-formulario">    
    <div class="formulario">
        <h1>Registrarse</h1>
        <form action="user_register" method="POST">
            <div class="campo">
                <label for="nombre">Ingrese Nombre de usuario:</label>
                <input type="text"  name="email" placeholder="Ingrese Nombre de usuario">
            </div>
            <div class="campo">
                <label for="email">Ingrese Contraseña:</label>
                <input type="pasword" name="password" placeholder="Ingrese Su Contraseña">
            </div>
            <div class="boton">
                <button>Registrarse</button>
            </div>
            <div class="invited">
                <a href="index">O Tambien puedes ingresar como invitado</a>   
            </div>
        </form>
    </div>
 </div>


<?php include_once('footer.tpl'); ?>
